name: benchmarks
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: codspeed-macro-staging
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install local version of pytest-codspeed
        run: pip install .
      - name: Run benchmarks
        uses: CodSpeedHQ/action@main
        with:
          run: pytest tests/benchmarks/ --codspeed
          upload-url: ${{ secrets.CODSPEED_UPLOAD_URL }}/upload
          runner-version: 3.1.0-beta.2
